
export default {
    'INCLUDES'          : 'includes',
    'NOT_INCLUDES'      : 'not includes',
    'EQUALS'            : '=',
    'NOT_EQUALS'        : '<>',
    'GREATER_THAN'      : '>',
    'GREATOR_OR_EQUALS' : '>=',
    'LESS_THAN'         : '<',
    'LESS_OR_EQUALS'    : '<=',
    'BETWEEN'           : 'between',
    'IN'                : 'in',
    'NOT_IN'            : 'not in',
    'IS_NULL'           : 'is null',
    'NOT_NULL'          : 'not null',
    'STARTS_WITH'       : 'starts with',
    'NOT_STARTS_WITH'   : 'not starts with',
    'ENDS_WITH'         : 'ends with',
    'NOT_ENDS_WITH'     : 'not ends with',
}