export default {
    ADD_ICON                : "AddIcon",
    CREATE_ICON             : "CreateIcon",
    REPORT_ICON             : "ReportIcon",
    VISIBILITY_ICON         : "VisibilityIcon",
    KEYBOARD_RETURN_ICON    : "KeyboardReturnIcon",
    FORWARD_ICON            : "ForwardIcon",
    FOLDER_ICON             : "FolderIcon",
    ARROW_FORWARD_ICON      : "ArrowForwardIcon",
    DONE_ICON               : "DoneIcon",
    EXIT_ICON               : "ExitToAppSharpIcon",
    ARROW_LEFT_ICON         : "ArrowLeftIcon",
    DELETE_ICON             : "DeleteIcon",
    EDIT_ICON               : "EditIcon",
}